/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moklet
 */
public class tammenu extends javax.swing.JFrame {
    int nol_jam ;
    int nol_menit ;
    int nol_detik ;

    /**
     * Creates new form tammenu
     */
    public tammenu() {
        initComponents();
        
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        makanan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        save1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESTORAN SEDERHANA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 20, 450, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 90);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setText("5. Nasi Lodeh(10K)");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 190, 150, 40);

        jLabel3.setText("Daftar Menu Minuman");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 10, 150, 50);

        jLabel4.setText("1. Soto Ayam(10K)");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 150, 40);

        jLabel5.setText("2. Soto Daging(12K)");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 100, 150, 40);

        jLabel6.setText("3. Gado - gado(15K)");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 130, 150, 40);

        jLabel7.setText("4. Nasi Campur(10K)");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 160, 150, 40);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(140, 0, 10, 250);

        jLabel8.setText("Daftar Menu Makanan");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 10, 150, 50);

        jLabel9.setText("1. Es Teh(5K)");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 70, 150, 40);

        jLabel10.setText("2. Es Jeruk(6K)");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(160, 100, 150, 40);

        jLabel11.setText("3. Es Teler(9K)");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(160, 130, 150, 40);

        jLabel12.setText("4. Es Kelapa Muda(8K)");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(160, 160, 150, 40);

        jLabel13.setText("5. Es Kacang Hijau(8K)");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(160, 190, 150, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(550, 90, 290, 250);

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setLayout(null);

        jLabel14.setText("Makanan/minuman");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(130, 70, 110, 40);
        jPanel4.add(makanan);
        makanan.setBounds(130, 100, 180, 30);

        jLabel15.setText("Tanggal Pemesanan");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(350, 10, 110, 40);
        jPanel4.add(harga);
        harga.setBounds(150, 40, 180, 30);

        jLabel16.setText("Jumlah");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(340, 70, 110, 40);
        jPanel4.add(jumlah);
        jumlah.setBounds(340, 100, 100, 30);

        jLabel17.setText("nomor makanan");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(40, 10, 110, 40);
        jPanel4.add(no);
        no.setBounds(40, 40, 80, 30);

        jLabel18.setText("Harga");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(150, 10, 110, 40);
        jPanel4.add(tanggal);
        tanggal.setBounds(350, 40, 190, 30);

        jLabel21.setText("Max. 2 item");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(450, 100, 80, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 90, 550, 160);

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));
        jPanel5.setLayout(null);

        save1.setText("Save");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel5.add(save1);
        save1.setBounds(10, 30, 110, 40);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel5.add(clear);
        clear.setBounds(140, 30, 110, 40);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel5.add(delete);
        delete.setBounds(280, 30, 110, 40);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel5.add(print);
        print.setBounds(420, 30, 110, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 250, 550, 90);

        jPanel6.setBackground(new java.awt.Color(204, 102, 255));
        jPanel6.setLayout(null);

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Makanan/Minuman", "Jumlah", "Harga", "Tanggal Pemesanan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(data);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 820, 240);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel6.add(refresh);
        refresh.setBounds(710, 260, 110, 40);

        jLabel19.setText("Tanggal ");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(40, 260, 180, 40);
        jPanel6.add(jLabel20);
        jLabel20.setBounds(340, 260, 280, 40);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 340, 840, 310);

        setSize(new java.awt.Dimension(858, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       no.setText("");
        makanan.setText("");
        harga.setText("");
        jumlah.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal1 = dateFormat.format(tanggal.getDate());
        
        if("".equals(no.getText())|| "".equals(makanan.getText())|| "".equals(harga.getText()) || "".equals(jumlah.getText()) || "".equals(tanggal1)){
           JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Warning", JOptionPane.WARNING_MESSAGE);
           }else{
           int jumlah1 = Integer.parseInt(jumlah.getText());
           int harga1 = Integer.parseInt(harga.getText());
           int harga2 ;
           if(jumlah1 == 2){
               harga2 = harga1*2;
             String SQL = "INSERT INTO tb_menu (no_makan,namamakan,hargamakan,jumlah,tanggal)" + "VALUES('"+no.getText()+"','"+makanan.getText()+"','"+harga2+"','"+jumlah.getText()+"','"+tanggal1+"')";
       int status = KoneksiDB.execute(SQL);
       if (status == 1){
           JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","OK", JOptionPane.INFORMATION_MESSAGE);
           selectData();  
       }
       else{
           JOptionPane.showMessageDialog(this,"Data gagal ditambahkan!","Warning",JOptionPane.WARNING_MESSAGE);
            }  
               
           }else if(jumlah1 == 3){
               harga2 = harga1*3;
               String SQL = "INSERT INTO tb_menu (no_makan,namamakan,hargamakan,jumlah,tanggal)" + "VALUES('"+no.getText()+"','"+makanan.getText()+"','"+harga2+"','"+jumlah.getText()+"','"+tanggal1+"')";
       int status = KoneksiDB.execute(SQL);
       if (status == 1){
           JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","OK", JOptionPane.INFORMATION_MESSAGE);
           selectData();  
       }
       else{
           JOptionPane.showMessageDialog(this,"Data gagal ditambahkan!","Warning",JOptionPane.WARNING_MESSAGE);
            }
               
           }else{
       String SQL = "INSERT INTO tb_menu (no_makan,namamakan,hargamakan,jumlah,tanggal)" + "VALUES('"+no.getText()+"','"+makanan.getText()+"','"+harga.getText()+"','"+jumlah.getText()+"','"+tanggal1+"')";
       int status = KoneksiDB.execute(SQL);
       if (status == 1){
           JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","OK", JOptionPane.INFORMATION_MESSAGE);
           selectData();  
       }
       else{
           JOptionPane.showMessageDialog(this,"Data gagal ditambahkan!","Warning",JOptionPane.WARNING_MESSAGE);
            }
       }
       }
    }//GEN-LAST:event_save1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int baris = data. getSelectedRow();
        if(baris != -1){
            String no = data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_menu WHERE no_makan='"+no+"'";
            
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
              JOptionPane.showMessageDialog(this, "Data berhasil dihapus","OK", JOptionPane.INFORMATION_MESSAGE);  
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","WARNING", JOptionPane.WARNING_MESSAGE);  
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih baris data","WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       MessageFormat header = new MessageFormat("KASIR RESTORAN SEDERHANA");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try{
            data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
            
        }catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tammenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tammenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tammenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tammenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tammenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTable data;
    private javax.swing.JButton delete;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField makanan;
    private javax.swing.JTextField no;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save1;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"no_makan","namamakan","hargamakan","jumlah"};
       DefaultTableModel dtm = new DefaultTableModel(null,kolom);
       
       String SQL = "SELECT * FROM tb_menu ";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String no_makan = rs.getString(1);
               String namamakan = rs.getString(2);
               String hargamakan = rs.getString(3);
               String jumlah = rs.getString(4);
               String data[] = {no_makan,namamakan,hargamakan,jumlah};
               dtm.addRow(data);
           }
           }
           catch(SQLException ex){
                   Logger.getLogger(tammenu.class.getName()).log(Level.SEVERE, null, ex);
                   }
           data.setModel(dtm);
        
    }

    private void setTanggal() {
        java.util.Date skg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        jLabel19.setText(kal.format(skg));
    }

    private void setJam() {
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt){
              Date dt = new Date() ;
                int nilai_jam = dt.getHours() ;
                int nilai_menit = dt.getMinutes() ;
                int nilai_detik = dt.getSeconds() ;
                if(nilai_jam <= 9){
                    
                 nol_jam = 0 ;   
                    
                } if(nilai_menit <= 9){
                    
                 nol_menit = 0 ;   
                    
                } if(nilai_jam <= 9){
                    
                 nol_detik = 0 ;   
                    
                }
                String jam = nol_jam + Integer.toString(nilai_jam) ;
                String menit = nol_menit + Integer.toString(nilai_menit) ;
                String detik = nol_detik + Integer.toString(nilai_detik) ;
                
                jLabel20.setText("Jam" + jam + ":" + menit + ":" + detik );
            }
            
        };
        
            new Timer(100, taskPerformer).start() ;  
            }
        }

